#!/sbin/runscript

depend() {
	need nagios
}

start() {
	ebegin "Starting ${SVCNAME}"
	start-stop-daemon --start \
		--pidfile /var/nagios/livestatusd.pid \
		--exec /usr/bin/thin -- \
		--pid /var/nagios/livestatusd.pid \
		--log /var/nagios/livestatusd.log \
		--rackup /etc/nagios/live.ru \
		--environment production \
		--port 6847 \
		--user nagios \
		--group nagios \
		--daemonize start
	eend $?
}

stop() {
	ebegin "Stopping ${SVCNAME}"
	start-stop-daemon --stop \
		--pidfile /var/nagios/livestatusd.pid
	eend $?
}
