#!/sbin/runscript

DAEMON=/opt/couchbase/bin/membase-server
PIDFILE=/opt/couchbase/var/lib/membase/membase-server.pid
NODEFILE=/opt/couchbase/var/lib/membase/membase-server.node
COOKIEFILE=/opt/couchbase/var/lib/membase/membase-server.cookie

start() {
	ebegin "Starting Couchbase Server"
	start-stop-daemon --start \
		--user couchbase --group couchbase \
		--pidfile ${PIDFILE} --exec ${DAEMON} \
		-- -- -noinput -detached
	eend $?
}

stop() {
	ebegin "Stopping Couchbase Server"
	start-stop-daemon --stop \
		--pidfile ${PIDFILE}
	eend $?
}
