#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)

# update gentoo eix cache
export PORTDIR=/usr/portage
export PORTDIR_OVERLAY=
eix-update -o ${TOPDIR}/eix.cache.gentoo

# update local eix cache
export PORTDIR=${TOPDIR}
export PORTDIR_OVERLAY=
eix-update -o ${TOPDIR}/eix.cache.zentoo

# output simplified eix-diff
export DIFF_FORMAT_ALL_NEW=
export CHAR_UPGRADE="\\>"
export CHAR_DOWNGRADE="\\<"
export DIFF_FORMATLINE_INSTALLEDVERSIONS=

eix-diff ${TOPDIR}/eix.cache.{zentoo,gentoo} | grep -v '^\[<\]'
