#!/bin/bash

set -e

# update repository
git pull -q origin master

# generate manifests for distribution and repoman sanity
repoman manifest

# update the metadata and use.local.desc files in the repo
egencache --update --update-use-local-desc --jobs=3 --portdir=$(pwd)

# update timestamps
touch metadata/timestamp.chk
