#!/bin/bash

TOPDIR=$(realpath $(dirname $0)/..)

export GENTOO_CACHE=${HOME}/cache/gentoo-portage

rsync --verbose \
	--recursive \
	--links \
	--safe-links \
	--perms \
	--times \
	--compress \
	--force \
	--whole-file \
	--delete \
	--exclude=/cache \
	--exclude=timestamp* \
	${GENTOO_CACHE}/metadata/ \
	${TOPDIR}/metadata/
